In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv('kucing11_baru.csv')
dataset.tail()

Ras  sering mengalami gatal-gatal  sering menggaruk-garuk tubuh  \
108    2                           1.0                             1   
109    2                           1.0                             1   
110    0                           1.0                             1   
111    0                           1.0                             1   
112    1                           1.0                             1   

     mengalami kemerahan pada kulit  memiliki kerak pada tubuh  \
108                               1                          1   
109                               1                          1   
110                               1                          1   
111                               1                          1   
112                               1                          1   

     mengalami lelah dan lemas  memiliki infeksi pada kulit  \
108                        0.0                          1.0   
109                        0.0                          1.0   
110                        0.0                          1.0   
111                        0.0                          1.0   
112                        0.0                          1.0   

     sering menjilati tubuhnya  memiliki bercak bersisik pada kulit  \
108                        0.0                                    0   
109                        0.0                                    0   
110                        0.0                                    0   
111                        0.0                                    0   
112                        0.0                                    0   

     sering menggelengkan kepala secara tidak wajar  ...  \
108                                               0  ...   
109                                               0  ...   
110                                               0  ...   
111                                               0  ...   
112                                               0  ...   

     mengalami bengkak pada bagian tubuh tertentu  bersin  \
108                                             0     0.0   
109                                             0     0.0   
110                                             0     0.0   
111                                             0     0.0   
112                                             0     0.0   

     mengalami gangguan pada pencernaan  sering menggigit  \
108                                   0               0.0   
109                                   0               0.0   
110                                   0               0.0   
111                                   0               0.0   
112                                   0               0.0   

     memiliki kotoran menumpuk di bagian telinga  \
108                                            0   
109                                            0   
110                                            0   
111                                            0   
112                                            0   

     sering dihinggapi tungau di bagian bulunya  \
108                                           0   
109                                           0   
110                                           0   
111                                           0   
112                                           0   

     memiliki cairan kecoklatan di bagian ekornya  \
108                                             0   
109                                             0   
110                                             0   
111                                             0   
112                                             0   

     memiliki butiran telur-telur tungau di bagian bulunya  \
108                                                  0       
109                                                  0       
110                                                  0       
111                                                  0       
112                      

In [ ]:
dataset['kucing sedang mengalami scabies'].value_counts()

0.0    69
1.0    44
Name: kucing sedang mengalami scabies, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score

In [ ]:
X = dataset.drop(labels='kucing sedang mengalami scabies', axis=1).values
y = dataset['kucing sedang mengalami scabies'].values

In [ ]:
np.unique(y, return_counts=True)

(array([0., 1.]), array([69, 44]))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=4)

print ('Train set:', X_train.shape, y_train.shape)
print ('Test set:', X_test.shape, y_test.shape)

Train set: (90, 22) (90,)
Test set: (23, 22) (23,)


In [ ]:
#Normalisasi
scaler = StandardScaler()
scaler.fit(X_train)

# Standardization Feature
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled[:5, :])

[[ 0.83479446  0.91473203  0.79772404  1.25356634  1.06904497 -0.65465367
   1.45032695  0.70710678  1.93309133  2.32992949  0.87447463  1.04547753
  -0.29040893 -0.21566555 -0.42919754 -0.46499055  1.45032695  1.1697953
   1.70676404 -0.24253563  1.87082869 -0.42919754]
 [ 0.83479446 -1.09321633 -1.25356634 -0.79772404 -0.93541435 -0.65465367
  -0.6894997  -1.41421356 -0.51730613 -0.42919754 -1.14354375 -0.95650071
  -0.29040893 -0.21566555 -0.42919754 -0.46499055  1.45032695 -0.85485041
  -0.58590407 -0.24253563 -0.53452248  2.32992949]
 [-0.37700395  0.91473203  0.79772404  1.25356634  1.06904497 -0.65465367
   1.45032695 -1.41421356 -0.51730613 -0.42919754  0.87447463  1.04547753
  -0.29040893 -0.21566555 -0.42919754 -0.46499055 -0.6894997  -0.85485041
  -0.58590407 -0.24253563 -0.53452248 -0.42919754]
 [-0.37700395  0.91473203  0.79772404 -0.79772404  1.06904497  1.52752523
  -0.6894997   0.70710678 -0.51730613  2.32992949  0.87447463  1.04547753
   3.44342023  4.63680925  2.32992

In [ ]:
#Membangun model SVM
classifier = SVC(kernel = 'linear', random_state = 0)

#Fit model SVM ke data
classifier.fit(X_train, y_train)

#Membuat prediksi
y_pred = classifier.predict(X_test)

In [ ]:
#Evaluasi Model SVM menggunakan metrices Accuracy
#Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

#Evaluasi performa model dengan accuracy
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

[[12  2]
 [ 1  8]]
Accuracy: 100.00 %


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

In [ ]:
model = SVC()
model.fit(X_train_scaled, y_train)

SVC()

In [ ]:
y_svm = model.predict(X_test_scaled)
print(classification_report(y_test, y_svm))

              precision    recall  f1-score   support

         0.0       0.93      0.93      0.93        14
         1.0       0.89      0.89      0.89         9

    accuracy                           0.91        23
   macro avg       0.91      0.91      0.91        23
weighted avg       0.91      0.91      0.91        23



In [ ]:
def race(Ras):
    if Ras =="Anggora":
        result = 0
    elif Ras =="Persia":
        result = 1
    elif Ras =="Lokal":
        result = 2
    return result

def gejala1(Gejala_1):
    if Gejala_1 =="Tidak":
        result = 0
    elif Gejala_1=="Ya":
        result = 1
    return result

def gejala2(Gejala_2):
    if Gejala_2 =="Tidak":
        result = 0
    elif Gejala_2=="Ya":
        result = 1
    return result

def gejala3(Gejala_3):
    if Gejala_3 =="Tidak":
        result = 0
    elif Gejala_3=="Ya":
        result = 1
    return result

def gejala4(Gejala_4):
    if Gejala_4 =="Tidak":
        result = 0
    elif Gejala_4=="Ya":
        result = 1
    return result

def gejala5(Gejala_5):
    if Gejala_5 =="Tidak":
        result = 0
    elif Gejala_5=="Ya":
        result = 1
    return result

def gejala6(Gejala_6):
    if Gejala_6 =="Tidak":
        result = 0
    elif Gejala_6=="Ya":
        result = 1
    return result

def gejala7(Gejala_7):
    if Gejala_7 =="Tidak":
        result = 0
    elif Gejala_7=="Ya":
        result = 1
    return result

def gejala8(Gejala_8):
    if Gejala_8 =="Tidak":
        result = 0
    elif Gejala_8=="Ya":
        result = 1
    return result

def gejala9(Gejala_9):
    if Gejala_9 =="Tidak":
        result = 0
    elif Gejala_9=="Ya":
        result = 1
    return result

def gejala10(Gejala_10):
    if Gejala_10 =="Tidak":
        result = 0
    elif Gejala_10=="Ya":
        result = 1
    return result

def gejala11(Gejala_11):
    if Gejala_11 =="Tidak":
        result = 0
    elif Gejala_11=="Ya":
        result = 1
    return result

def gejala12(Gejala_12):
    if Gejala_12 =="Tidak":
        result = 0
    elif Gejala_12=="Ya":
        result = 1
    return result

def gejala13(Gejala_13):
    if Gejala_13 =="Tidak":
        result = 0
    elif Gejala_13=="Ya":
        result = 1
    return result

def gejala14(Gejala_14):
    if Gejala_14 =="Tidak":
        result = 0
    elif Gejala_14=="Ya":
        result = 1
    return result

def gejala15(Gejala_15):
    if Gejala_15 =="Tidak":
        result = 0
    elif Gejala_15=="Ya":
        result = 1
    return result

def gejala16(Gejala_16):
    if Gejala_16 =="Tidak":
        result = 0
    elif Gejala_16=="Ya":
        result = 1
    return result

def gejala17(Gejala_17):
    if Gejala_17 =="Tidak":
        result = 0
    elif Gejala_17=="Ya":
        result = 1
    return result

def gejala18(Gejala_18):
    if Gejala_18 =="Tidak":
        result = 0
    elif Gejala_18=="Ya":
        result = 1
    return result

def gejala19(Gejala_19):
    if Gejala_19 =="Tidak":
        result = 0
    elif Gejala_19=="Ya":
        result = 1
    return result

def gejala20(Gejala_20):
    if Gejala_20 =="Tidak":
        result = 0
    elif Gejala_20=="Ya":
        result = 1
    return result

def gejala21(Gejala_21):
    if Gejala_21 =="Tidak":
        result = 0
    elif Gejala_21=="Ya":
        result = 1
    return result

In [ ]:
# input data baru
Ras = "Anggora" #@param ["Anggora", "Persia", "Lokal"]
Ras = race(Ras)
#sering mengalami gatal-gatal
Gejala_1 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_1 = gejala1(Gejala_1)
#Sering Menggaruk-Garuk Tubuh
Gejala_2 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_2 = gejala2(Gejala_2)
#Mengalami Kemerahan Pada Kulit
Gejala_3 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_3 = gejala3(Gejala_3)
#Memiliki Kerak Pada Tubuh
Gejala_4 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_4 = gejala4(Gejala_4)
#Mengalami Lelah Dan Lemas
Gejala_5 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_5 = gejala5(Gejala_5)
#Memiliki Infeksi Pada Kulit
Gejala_6 = "Ya" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_6 = gejala6(Gejala_6)
#Sering Menjilati Tubuhnya
Gejala_7 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_7 = gejala7(Gejala_7)
#Memiliki Bercak Bersisik Pada Kulit
Gejala_8 = "Ya" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_8 = gejala8(Gejala_8)
#Sering Menggelengkan Kepala Secara Tidak Wajar
Gejala_9 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_9 = gejala9(Gejala_9)
#Bulu Rontok
Gejala_10 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_10 = gejala10(Gejala_10)
#Memiliki Luka Pada Bagian Tubuh Tertentu
Gejala_11 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_11 = gejala11(Gejala_11)
#Memiliki Ekor Yang Berminyak
Gejala_12 = "Ya" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_12 = gejala12(Gejala_12)
#Mengalami Bengkak Pada Bagian Tubuh Tertentu
Gejala_13 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_13 = gejala13(Gejala_13)
#Bersin
Gejala_14 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_14 = gejala14(Gejala_14)
#Mengalami Gangguan Pada Pencernaan
Gejala_15 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_15 = gejala15(Gejala_15)
#Sering Menggigit
Gejala_16 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_16 = gejala16(Gejala_16)
#Memiliki Kotoran Menumpuk Di Bagian Telinga
Gejala_17 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_17 = gejala17(Gejala_17)
#Sering Dihinggapi Tungau Di Bagian Bulunya
Gejala_18 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_18 = gejala18(Gejala_18)
#Memiliki Cairan Kecoklatan Di Bagian Ekornya
Gejala_19 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_19 = gejala19(Gejala_19)
#Memiliki Butiran Telur-Telur Tungau Di Bagian Bulunya
Gejala_20 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_20 = gejala20(Gejala_20)
#Kucing Pernah Mengalami Scabies
Gejala_21 = "Tidak" #@param ["Ya","Tidak"]{type:"string"} 
Gejala_21 = gejala21(Gejala_21)

# data baru yang diinput harus di-standardization terlebih dahulu
data_baru = [[Ras, Gejala_1,Gejala_2,Gejala_3,Gejala_4,Gejala_5,Gejala_6,Gejala_7,Gejala_8,Gejala_9,Gejala_10,Gejala_11,Gejala_12,Gejala_13,Gejala_14,Gejala_15,Gejala_16,Gejala_17,Gejala_18,Gejala_19,Gejala_20,Gejala_21]]
data_baru = scaler.transform(data_baru)

# prediksi data baru, yang sudah di-standardization
hasil_prediksi = model.predict(data_baru)
hasil_prediksi = int (hasil_prediksi)

# probabilitas prediksi


# hasil prediksi
print(f'Gejala tersebut diprediksi kucing ', end='')
if hasil_prediksi == 0:
  print('tidak scabies')
elif hasil_prediksi == 1:
  print('scabies')

Gejala tersebut diprediksi kucing tidak scabies


In [ ]:
data_baru

array([[-0.37700395,  0.91473203,  0.79772404,  1.25356634,  1.06904497,
        -0.65465367,  1.45032695, -1.41421356, -0.51730613, -0.42919754,
        -1.14354375,  1.04547753, -0.29040893, -0.21566555, -0.42919754,
        -0.46499055, -0.6894997 , -0.85485041, -0.58590407, -0.24253563,
        -0.53452248, -0.42919754]])

In [ ]:
# save model untuk deploy
import joblib
import pickle

In [ ]:
pickle.dump(scaler, open('scaler_ds.pkl', 'wb'))
pickle.dump(model, open('model_ds.pkl', 'wb'))